# This is a basic workflow to help you get started with Actions
name: InvokePy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Deploy code to Lambda Function
        uses: cmd-not-found/aws-lambda-pyscript@main
        with:
          lambda_function_name: ${{ secrets.LAMBDA_FUNCTION_NAME }}
          lambda_region: ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
  linux_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: step1
        run: echo "Hello, $USER!"
      - name: step2
        run: ls -lsa
  python_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: hello user
        run: echo "Hello, $USER!"
      - name: query directory
        run: ls -lsa
      - name: pip install boto3
        run: pip install boto3
      - name: invoke py
        run: python py-test.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
