# This is a basic workflow to help you get started with Actions
name: InvokePy
# Controls when the action will run.
on: push
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
  linux_job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello, $USER!"
      - name: step2
        run: ls -lsa
  python_job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello, $USER!"
      - name: step2
        run: ls -lsa
      - name: step3
        run: python py-test.py
